# -*- coding: utf-8 -*-
"""Support_Information_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dlxMCca8yrwroke6WiI1qstlzo-AH4g

# 🤖 Support Information Assistant — Gen AI Multi-Agent System

## Overview
* A Generative AI powered customer support assistant that helps users retrieve customer information and company policy details using natural language questions.

* The system uses SQL database for customer data and a vector database for searching policy documents.

The system uses:
- SQLite database for customer profiles and support tickets
- Chroma vector database for policy document search
- LangGraph for agent workflow management
- Groq LLM for generating responses
- Streamlit for the user interface

## Features

- Customer profile lookup
- Support ticket retrieval
- Policy document search
- AI-generated responses
- Natural language interaction
"""

#Install Dependencies
!pip install -q langchain langgraph langchain-groq langchain-community \
chromadb langchain-huggingface pypdf sentence-transformers
!pip install -q langchain-chroma
!pip install -q mcp

#Install GROQ API Key
import os, getpass
os.environ["GROQ_API_KEY"] = getpass.getpass("Enter GROQ API KEY: ")
print("✅ Groq API key added")

import os
BASE = "support_copilot"
DATA_DIR = f"{BASE}/data"
os.makedirs(DATA_DIR, exist_ok=True)

DB_PATH = f"{DATA_DIR}/support.db"
CHROMA_DIR = f"{DATA_DIR}/chroma_db"
print("✅ Paths ready")

import os

if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

import sqlite3

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS customers(
id INTEGER,
name TEXT,
email TEXT,
plan TEXT
)
""")

cur.execute("DELETE FROM customers")

cur.executemany(
    "INSERT INTO customers VALUES (?,?,?,?)",
    [
        (1,"Ema Watson","ema@email.com","Premium"),
        (2,"Alex","alex@email.com","Basic"),
        (3,"Sarah","sarah@email.com","Standard")
    ]
)

cur.execute("""
CREATE TABLE IF NOT EXISTS support_tickets(
id INTEGER,
customer_id INTEGER,
issue TEXT,
status TEXT
)
""")

cur.execute("DELETE FROM support_tickets")

cur.executemany(
    "INSERT INTO support_tickets VALUES (?,?,?,?)",
    [
        (1,1,"Payment issue","Open"),
        (2,1,"Login problem","Resolved"),
        (3,2,"Shipping delay","Open")
    ]
)

conn.commit()
conn.close()

from pathlib import Path

POLICY_DIR = Path("support_copilot/data/policies")
POLICY_DIR.mkdir(parents=True, exist_ok=True)

policies = {
    "refund_policy.txt": "Refund available within 30 days of purchase.",
    "shipping_policy.txt": "Shipping takes 5-8 business days.",
    "warranty_policy.txt": "Products have 12-month warranty."
}

for file, content in policies.items():
    with open(POLICY_DIR / file, "w") as f:
        f.write(content)

print("✅ Policies created")

from langchain_community.document_loaders import TextLoader
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

docs = []

for file in os.listdir(POLICY_DIR):
    loader = TextLoader(f"{POLICY_DIR}/{file}")
    docs.extend(loader.load())

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory=CHROMA_DIR
)

print("✅ Policy knowledge base created")

import sqlite3
def get_customer(name):

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    cur.execute(
        """
        SELECT
        customers.name,
        customers.email,
        customers.plan,
        support_tickets.issue,
        support_tickets.status

        FROM customers

        LEFT JOIN support_tickets

        ON customers.id = support_tickets.customer_id

        WHERE customers.name LIKE ?
        """,
        (f"%{name}%",)
    )

    result = cur.fetchall()
    conn.close()
    return result

def search_policy(query):
    results = vectorstore.similarity_search(query, k=2)
    return results

print("✅ Tools ready")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mcp_server.py
# 
# import sqlite3
# from mcp.server.fastmcp import FastMCP
# 
# mcp = FastMCP("support-tools")
# DB_PATH = "support_copilot/data/support.db"
# 
# @mcp.tool()
# def get_customer_info(name: str):
#     """
#     Get customer information from SQL database.
#     """
# 
#     conn = sqlite3.connect(DB_PATH)
#     cursor = conn.cursor()
# 
#     cursor.execute(
#         "SELECT * FROM customers WHERE name LIKE ?",
#         (f"%{name}%",)
#     )
# 
#     result = cursor.fetchall()
#     conn.close()
# 
#     if not result:
#         return "Customer not found"
# 
#     return str(result)
# 
# @mcp.tool()
# def search_policy(query: str):
#     """
#     Search company policy documents.
#     """
#     # Later connect Chroma vector search here
#     return f"Searching policy documents for: {query}"
# 
# if __name__ == "__main__":
#     mcp.run(transport="stdio")

from typing import TypedDict, Optional
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq


def build_llm():
    return ChatGroq(
        model="llama-3.1-8b-instant",
        temperature=0
    )

class GraphState(TypedDict):
    question: str
    route: str
    result: Optional[str]

llm = build_llm()

def router(state):
    q = state["question"].lower()

    if "refund" in q or "policy" in q or "shipping" in q:
        return {"route": "rag"}

    return {"route": "sql"}

def sql_agent(state):
    if state["route"] == "sql":

        name = "Ema"

        result = get_customer(name)

        return {"result": str(result)}

def rag_agent(state):
    if state["route"] == "rag":
        result = search_policy(state["question"])
        return {"result": str(result)}
    return {}

def final_answer(state):
    response = llm.invoke(
        f"""
        Answer user question using this information:

        {state.get('result')}

        Question:
        {state['question']}
        """
    )

    return {"result": response.content}

graph = StateGraph(GraphState)

graph.add_node("router", router)
graph.add_node("sql_agent", sql_agent)
graph.add_node("rag_agent", rag_agent)
graph.add_node("final", final_answer)

graph.set_entry_point("router")

graph.add_edge("router", "sql_agent")
graph.add_edge("sql_agent", "rag_agent")
graph.add_edge("rag_agent", "final")
graph.add_edge("final", END)


support_graph = graph.compile()
print("✅ Multi-agent system ready")

docs = []

for file in os.listdir(POLICY_DIR):
    loader = TextLoader(f"{POLICY_DIR}/{file}")
    docs.extend(loader.load())

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory=CHROMA_DIR
)

print("✅ Policy knowledge base created")

async def ask(question):

    result = await support_graph.ainvoke({
        "question": question,
        "route": "",
        "result": None
    })

    print(result["result"])

# 10. Try it out
await ask("Give me a quick overview of customer Ema's profile and past support ticket details.")

# 11. Try a policy (RAG) question
await ask("What is the current refund policy?")

# 12. A question needing BOTH agents
await ask("Ema has an open technical ticket — what is our warranty policy in case it turns out to be a hardware defect?")

"""#Streamlit Part"""

!pip install -q streamlit pyngrok
!pip install -q pyngrok

!pip install -q streamlit pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("3CvtgJoxl0KmmUeM1nbO3fFCQmp_2s3uRbbbhTuZFCSdFHJkD")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import os
# import asyncio
# import sqlite3
# import streamlit as st
# 
# from langchain_groq import ChatGroq
# from langchain_chroma import Chroma
# from langchain_huggingface import HuggingFaceEmbeddings
# from langchain_community.document_loaders import TextLoader
# 
# from langgraph.graph import StateGraph, END
# from typing import TypedDict, Optional
# 
# 
# os.environ["GROQ_API_KEY"] = "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"
# DB_PATH = "support.db"
# 
# 
# # ---------- DATABASE ----------
# 
# conn = sqlite3.connect(DB_PATH)
# cur = conn.cursor()
# 
# cur.execute("""
# CREATE TABLE IF NOT EXISTS customers(
# id INTEGER,
# name TEXT,
# email TEXT,
# plan TEXT
# )
# """)
# 
# cur.execute("DELETE FROM customers")
# 
# cur.executemany(
#     "INSERT INTO customers VALUES (?,?,?,?)",
#     [
#         (1,"Ema Watson","ema@email.com","Premium"),
#         (2,"Alex","alex@email.com","Basic"),
#         (3,"Sarah","sarah@email.com","Standard")
#     ]
# )
# 
# cur.execute("""
# CREATE TABLE IF NOT EXISTS support_tickets(
# id INTEGER,
# customer_id INTEGER,
# issue TEXT,
# status TEXT
# )
# """)
# 
# cur.execute("DELETE FROM support_tickets")
# 
# cur.executemany(
#     "INSERT INTO support_tickets VALUES (?,?,?,?)",
#     [
#         (1,1,"Login problem","Resolved"),
#         (2,1,"Payment issue","Open")
#     ]
# )
# 
# conn.commit()
# conn.close()
# 
# 
# def get_customer(name):
#     conn = sqlite3.connect(DB_PATH)
#     cur = conn.cursor()
# 
#     cur.execute(
#         """
#         SELECT
#         customers.name,
#         customers.email,
#         customers.plan,
#         support_tickets.issue,
#         support_tickets.status
# 
#         FROM customers
# 
#         LEFT JOIN support_tickets
# 
#         ON customers.id = support_tickets.customer_id
# 
#         WHERE customers.name LIKE ?
#         """,
#         (f"%{name}%",)
#     )
# 
#     result = cur.fetchall()
#     conn.close()
#     return result
# 
# # ---------- LLM ----------
# 
# llm = ChatGroq(
#     model="llama-3.1-8b-instant",
#     temperature=0
# )
# 
# # ---------- LANGGRAPH ----------
# 
# class State(TypedDict):
# 
#     question: str
#     result: Optional[str]
# 
# def agent(state):
# 
#     data = get_customer("Ema")
# 
#     response = llm.invoke(
#         f"""
#         You are a customer support assistant.
#         Use this customer profile and ticket information:
# 
#         {data}
# 
#         Answer the user question clearly.
#         Include customer details and past support tickets if available.
# 
#         Question:
#         {state['question']}
#         """
#     )
# 
#     return {
#         "result": response.content
#     }
# 
# graph = StateGraph(State)
# 
# graph.add_node(
#     "agent",
#     agent
# )
# 
# graph.set_entry_point("agent")
# 
# graph.add_edge(
#     "agent",
#     END
# )
# 
# app_graph = graph.compile()
# 
# async def ask(question):
# 
#     result = await app_graph.ainvoke(
#         {
#             "question": question,
#             "result": ""
#         }
#     )
# 
#     return result["result"]
# 
# # ---------- STREAMLIT ----------
# 
# st.title("🤖 Support Information Assistant")
# question = st.text_input("Ask")
# 
# if st.button("Submit"):
# 
#     answer = asyncio.run(
#         ask(question)
#     )
# 
#     st.write(answer)

!pkill -f streamlit
!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

url = ngrok.connect(8501)
print(url)

!pkill -f ngrok